### ISSUE TITLE
Android Back Button Issue

### ISSUE THREAD

**Issue by BuffMcBigHuge** [vickramravichandran/angular-auto-complete#14]
When typing on Android, pressing the back button to dismiss the keyboard also closes the results, making it frustrating to select an item.

**Comment by vickramravichandran** [comment]
When you say 'back button' do you mean Backspace? If yes, I don't see the behavior you describe when I hit the Backspace key. Here is a screencast I created using my Android phone: 

https://www.youtube.com/watch?v=fl96DL9cysQ

**Comment by vickramravichandran** [comment]
It is caused by the window resize. https://github.com/vickramravichandran/angular-auto-complete/blob/master/angular-auto-complete.js#L183

I will publish a version with the following options:

- `hideDropdownOnWindowResize` (default true) 
- `autoHideDropdown` (default true) Also see `hideDropdown()` method below.

I will add a `ready` callback that occurs after the plugin is initialized and ready. The callback receives an object with the following methods:

- `setOptions({key: value})`: Sets the supplied options on the plugin. The method takes an object hash of key/value pairs where key is any valid option name.
- `positionDropdown()`: Positions the dropdown list.
- `hideDropdown()`: Hides the dropdown list.

**Comment by vickramravichandran** [comment]
I have published `v1.6.0` to npm. Let me know if setting `hideDropdownOnWindowResize` to `false` solves the issue.

**Comment by BuffMcBigHuge** [comment]
Works wonderfully. Thank you kind sir!
