### ISSUE TITLE
Label on input is not updated on Angular 1.7.8

### ISSUE THREAD

**Issue by phackwer** [vickramravichandran/angular-auto-complete#29]
Hi,

When we use the keyboard to navigate the itens that are listed, the input field is emptied instead of presenting the name of the item selected in the list. This seems to be an issue on Angular 1.7.8 forward (I can't tell by the others). We used the selectedTextAttr: 'name', and return the objects with uuid and name attributes, still no luck. Any ideas?

![image](https://user-images.githubusercontent.com/4871786/62128429-50ca0480-b2cc-11e9-9cbf-38c8700fa201.png)

![image](https://user-images.githubusercontent.com/4871786/62128443-56274f00-b2cc-11e9-87f1-ea7b85e12402.png)

**Comment by phackwer** [comment]
Sorry, just noticed the error was mine, the renderItem is the place to actually get the rendered selected item in the text input

**Comment by vickramravichandran** [comment]
Nice to know you were able to get it to work with `renderItem` callback. The `selectedTextAttr` should also work the way you described. The "Custom List" sample of colors on my demo site seems like your use case. I use `code` instead of `uuid` though.

See 2nd example "Custom List" in the demo site https://demo.vickram.me/angular-auto-complete/
